<?php include "header.phtml"; ?>
            <li class="breadcrumb-item active" aria-current="page">Question details</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>New question / Edit question</h1>
        </div>

        <!--Question details form-->
        <form action="<?php
        if (isset($question))
            echo '/question/add/'.$question->getId().'" method="POST">';
        else
            echo '/question/add'.'" method="POST">';
        if (isset($question)) {
            echo '<div class="form-group">
                    <label 
                    for="questionName">Question text
                    </label>
                    <textarea 
                    type="text"
                    class="form-control"
                    id="questionName"
                    name="question">' . $question->getText() .'</textarea>
                </div>
                <div class="form-group">
                    <label
                    for="questionAnswer">Question Answer
                    </label>
                    <textarea
                    type="text"
                    class="form-control"
                    id="questionAnswer"
                    name="answer">'. $answer->getText().'</textarea>
                </div>';
        } else {
            echo '<div class="form-group">
                    <label
                    for="questionName">Question
                    </label>
                    <textarea
                    type="text"
                    class="form-control"
                    id="questionName"
                    name="question">Type in your question</textarea>
                    <label
                    for="questionAnswer">Question Answer
                    </label>
                    <textarea
                    type="text"
                    class="form-control"
                    id="questionAnswer"
                    name="answer">Leave empty, if needed.</textarea>
                </div>';
        }
        ?>
            <div class="form-group">
                <label for="questionType">Type</label>
                <select class="form-control" id="questionType" name="type">
                    <option value="text">text</option>
                </select>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Save question</button>
            </div>
        </form>
    </div>
</body>
</html>