<?php include 'header.phtml'; ?>
            <li class="breadcrumb-item active" aria-current="page">Quizzes listing</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Quizzes listing</h1>
        </div>

        <!--Table actions block-->
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="">
                    <label for="quizSearch">Quiz name search</label>
                    <div class="input-group">
                        <input type="text" id="quizSearch" class="form-control" placeholder="">
                        <div class="input-group-append">
                            <button class="btn btn-secondary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-12 col-md-6 d-flex align-items-end justify-content-end">
                <a class="btn btn-primary py-1" href="/quiz/add">Add new quiz</a>
            </div>
        </div>

        <!--Quiz listing table-->
        <div class="table-responsive my-4">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <!--Sorting arrow are displayed using the 'asc','dsc' classes-->
                    <th scope="col">ID</th>
                    <th scope="col" class="sorting-header <?php
                    if ($urlHelper->getValue("sort") === "asc"): echo "asc"; endif;
                    if ($urlHelper->getValue("sort") === "dsc"): echo "dsc"; endif;
                    if (!$urlHelper->keyExists("sort")): echo "asc dsc"; endif;
                    ?>">
                        <a style="display: block; width: 100%; height: 100%;" href="/quiz<?php echo $urlHelper->getNextSortStateUrl();?>">Email</a>
                    </th>
                    <th scope="col">Type</th>
                    <th scope="col">Created By</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php
                    if (isset($entities)):
                        foreach ($entities as $key => $values): ?>
                            <tr>
                                <td><?php echo $values->getId(); ?></td>
                                <td><?php echo $values->getName();?></td>
                                <td><?php echo $values->getType();?></td>
                                <td><?php echo $values->getCreatedBy();?></td>
                                <td class="text-center">
                                    <a class="btn btn-primary py-1" href="/quiz/add/<?php echo $values->getId();?>">Edit</a>
                                    <a class="btn btn-danger py-1" href="/quiz/delete/<?php echo $values->getId();?>">Delete</a>
                                </td>
                            </tr>
                <?php  endforeach; endif; ?>
                </tbody>
            </table>
        </div>

        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item <?php if ($paginator->getCurrentPage() === 1): echo "disabled"; endif;?>">
                    <a class="page-link" href="<?php if ($paginator->getPreviousPage()): echo "/quiz?page=".$paginator->getPreviousPage(); endif;?>" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                <?php
                $page = 1;
                while ($page <= $paginator->getTotalpages()):
                    ?>
                    <li class="page-item <?php if($page === $paginator->getCurrentPage()): echo "active"; endif;?>"><a class="page-link" href="/quiz?page=<?php echo $page;?>"><?php echo $page;?></a></li>
                    <?php
                    $page++;
                endwhile;?>
                <li class="page-item <?php if ($paginator->getCurrentPage() === $paginator->getTotalpages()): echo "disabled"; endif;?>">
                    <a class="page-link" href="<?php if ($paginator->getNextPage()): echo "/quiz?page=".$paginator->getNextPage(); endif;?>">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>