<?php include 'header.phtml'; ?>
            <li class="breadcrumb-item active" aria-current="page">Users listing</li>
        </ol>
    </nav>

<div class="container-fluid">
    <div style="
        float: right;
        position: -webkit-sticky; /* Safari */
        position: sticky;
        margin-top: 56px;
        margin-right: 220px;
        top: 150px;"
    >
        <a class="btn btn-primary py-1 mb-3" href="/user">Reset Search</a>
    </div>
    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Users listing</h1>
        </div>

        <!--Table actions block-->
        <div class="row">
            <div class="col-12 col-md-12 d-flex align-items-end justify-content-end">
                <a class="btn btn-primary py-1 mb-3" href="/user/add">Add new user</a>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6">
                <label for="roleSearch">User role select</label>
                <select class="form-control" id="roleSearch" onchange="location = this.value">
                    <option value="user<?php echo $urlHelper->getUrlForFilter("role", "all");?>" <?php if($urlHelper->getValue("role") !== 'admin' && $urlHelper->getValue("role") !== 'user') echo "selected";?>>all</option>
                    <option value="user<?php echo $urlHelper->getUrlForFilter("role", "admin");?>" <?php if($urlHelper->getValue("role") === 'admin') echo "selected";?>>admin</option>
                    <option value="user<?php echo $urlHelper->getUrlForFilter("role", "user");?>" <?php if($urlHelper->getValue("role") === 'user') echo "selected";?>>user</option>
                </select>
            </div>
            <div class="col-12 col-md-6">
                <form action="user" method="GET">
                    <label for="emailSearch">Email search</label>
                    <div class="input-group">
                        <input type="text" id="emailSearch" class="form-control" name="email" placeholder="user@domain.something">
                        <div class="input-group-append">
                            <button class="btn btn-secondary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <!--Quiz listing table-->
        <div class="table-responsive my-4">
            <?php if($message->isSet()): ?>
                <div class="alert alert-<?php echo ($message->isSuccess()) ? "success" : "error";?>">
                    <strong>Info!</strong> <?php echo $message->getMessage(); $message->deleteMessage();?>
                </div>
            <?php endif;?>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <!--Sorting arrow are displayed using the 'asc','dsc' classes-->
                    <th>ID</th>
                    <th scope="col" class="sorting-header <?php
                        if ($urlHelper->getValue("sort") === "asc"): echo "asc"; endif;
                        if ($urlHelper->getValue("sort") === "dsc"): echo "dsc"; endif;
                        if (!$urlHelper->keyExists("sort")): echo "asc dsc"; endif;
                    ?>">
                        <a style="display: block; width: 100%; height: 100%;" href="/user<?php echo $urlHelper->getNextSortStateUrl();?>">Email</a>
                    </th>
                    <th scope="col">Role</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php
                if ($entities):
                    foreach ($entities as $key => $values): ?>
                        <tr>
                            <td><?php echo $values->getId(); ?></td>
                            <td><?php echo $values->getName(); ?></td>
                            <td><?php echo $values->getRole(); ?></td>
                            <td class="text-center">
                                <a class="btn btn-primary py-1" href="/user/add/<?php echo $values->getId(); ?>">Edit</a>
                                <a class="btn btn-danger py-1" href="/user/delete/<?php echo $values->getId(); ?>">Delete</a>
                            </td>
                        </tr>
                 <?php endforeach; endif;?>
                </tbody>
            </table>
        </div>
        <!--Pagination block-->
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item <?php if ($paginator->getCurrentPage() === 1): echo "disabled"; endif;?>">
                    <a class="page-link" href="/user<?php echo $urlHelper->getPreviousPageUrl();?>" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                <?php
                $page = 1;
                while ($page <= $paginator->getTotalpages()):
                    ?>
                    <li class="page-item <?php
                    if($page === $paginator->getCurrentPage()): echo "active"; endif;?>"><a class="page-link" href="/user<?php echo $urlHelper->getUrlForPage($page);?>"><?php echo $page;?></a></li>
                    <?php
                    $page++;
                endwhile;?>
                <li class="page-item <?php if ($paginator->getCurrentPage() === $paginator->getTotalPages()): echo "disabled"; endif;?>">
                    <a class="page-link" href="user<?php echo $urlHelper->getNextPageUrl();?>">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</div>
</body>
</html>