<?php include 'header.phtml'; ?>
            <li class="breadcrumb-item active" aria-current="page">Users listing</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Users listing</h1>
        </div>

        <!--Table actions block-->
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="">
                    <div class="form-group">
                        <label for="roleSearch">User role select</label>
                        <select class="form-control" id="roleSearch">
                            <option>admin</option>
                            <option>user</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="col-12 col-md-6 d-flex align-items-end justify-content-end">
                <a class="btn btn-primary py-1 mb-3" href="/user/add">Add new user</a>
            </div>
        </div>

        <!--Quiz listing table-->
        <div class="table-responsive my-4">
            <?php if(isset($message)): ?>
                <div class="alert alert-info">
                    <strong>Info!</strong> <?php echo $message ?>
                </div>
            <?php endif;?>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <!--Sorting arrow are displayed using the 'asc','dsc' classes-->
                    <th scope="col" class="sorting-header asc dsc">ID</th>
                    <th scope="col">Email</th>
                    <th scope="col">Role</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php
                if ($entities):
                    foreach ($entities as $key => $values): ?>
                        <tr>
                            <td><?php echo $values->getId(); ?></td>
                            <td><?php echo $values->getName(); ?></td>
                            <td><?php echo $values->getRole(); ?></td>
                            <td class="text-center">
                                <a class="btn btn-primary py-1" href="/user/add/<?php echo $values->getId(); ?>">Edit</a>
                                <a class="btn btn-danger py-1" href="/user/delete/<?php echo $values->getId(); ?>">Delete</a>
                            </td>
                        </tr>
                 <?php endforeach; endif;?>
                </tbody>
            </table>
        </div>

        <!--Pagination block-->
        <?php
        $currentPage = $paginator->getCurrentPage();
        $nrOfPages = $paginator->getTotalpages();
        $nextPage = $paginator->getNextPage();
        $previousPage = $paginator->getPreviousPage();
        ?>

        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">

                <li class="page-item <?php if ($currentPage === 1): echo "disabled"; endif;?>">
                    <a class="page-link" href="<?php if ($previousPage): echo "http://local.quiz.com/user?page=".$previousPage; endif;?>" tabindex="-1" aria-disabled="true">Previous</a>
                </li>

                <?php
                $page = 1;
                while ($page <= $nrOfPages):
                    ?>
                    <li class="page-item <?php if($page === $currentPage): echo "active"; endif;?>"><a class="page-link" href="http://local.quiz.com/user?page=<?php echo $page;?>"><?php echo $page;?></a></li>
                    <?php
                    $page++;
                endwhile;?>
                <li class="page-item <?php if ($currentPage === $nrOfPages): echo "disabled"; endif;?>">
                    <a class="page-link" href="<?php if ($nextPage): echo "http://local.quiz.com/user?page=".$nextPage; endif;?>">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>