<!DOCTYPE html>
<html lang="en">
<head>
    <!--Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--Libraries used by Bootstrap-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <!--Font awesome CSS-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!--Bootstrap JS-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!--Custom css-->
    <link rel="stylesheet" href="../../public/assets/css/custom-css.css">

    <title>Admin - Quizzes listing</title>
</head>

<body>
    <!--Header-->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 mb-3 bg-light border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">QuizApp</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <span class="p-2 text-dark">Hello, <?php echo $session->get('name'); ?></span>
        </nav>
        <a class="btn btn-secondary" href="/logout">Logout</a>
    </div>

    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item" ><a href="/">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Quizzes listing</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Quizzes listing</h1>
        </div>

        <!--Table actions block-->
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="">
                    <label for="quizSearch">Quiz name search</label>
                    <div class="input-group">
                        <input type="text" id="quizSearch" class="form-control" placeholder="">
                        <div class="input-group-append">
                            <button class="btn btn-secondary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-12 col-md-6 d-flex align-items-end justify-content-end">
                <a class="btn btn-primary py-1" href="/quiz/add">Add new quiz</a>
            </div>
        </div>

        <!--Quiz listing table-->
        <div class="table-responsive my-4">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <!--Sorting arrow are displayed using the 'asc','dsc' classes-->
                    <th scope="col" class="sorting-header asc dsc">ID</th>
                    <th scope="col">Quiz</th>
                    <th scope="col">Description</th>
                    <th scope="col">Questions number</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>asd asad asdadadsad</td>
                    <td>azxczxc cxzc</td>
                    <td>1</td>
                    <td class="text-center">
                        <a class="btn btn-primary py-1" href="#">Edit</a>
                        <a class="btn btn-danger py-1" href="#">Delete</a>
                    </td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>asd asad asdadadsad</td>
                    <td>azxczxc cxzc</td>
                    <td>2</td>
                    <td class="text-center">
                        <a class="btn btn-primary py-1" href="#">Edit</a>
                        <a class="btn btn-danger py-1" href="#">Delete</a>
                    </td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>asd asad asdadadsad</td>
                    <td>azxczxc cxzc</td>
                    <td>3</td>
                    <td class="text-center">
                        <a class="btn btn-primary py-1" href="#">Edit</a>
                        <a class="btn btn-danger py-1" href="#">Delete</a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

        <!--Pagination block-->
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item active"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>