<!DOCTYPE html>
<html lang="en">
<head>
    <!--Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--Libraries used by Bootstrap-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <!--Font awesome CSS-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!--Bootstrap JS-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!--Custom css-->
    <link rel="stylesheet" href="../../public/assets/css/custom-css.css">

    <title>Admin - dashboard</title>
</head>

<body>
    <!--Header-->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 mb-3 bg-light border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">QuizApp</h5>
        <a class="btn btn-secondary" href="#">Logout</a>
    </div>

    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item active" aria-current="page"><a href="#">Dashboard</a></li>
        </ol>
    </nav>

    <!--Main content-->
    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Welcome, <?php echo $session->get('name');?>!</h1>
            <a href="#" class="btn btn-primary m-2">Quizzes</a>
            <a href="#" class="btn btn-primary m-2">Users</a>
            <a href="#" class="btn btn-primary m-2">Questions</a>
            <a href="#" class="btn btn-primary m-2">Results</a>
        </div>
    </div>
</body>
</html>