<?php include "header.phtml"; ?>
            <li class="breadcrumb-item active" aria-current="page">Questions listing</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Questions listing</h1>
        </div>

        <!--Table actions block-->
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="">
                    <label for="textSearch">Text search</label>
                    <div class="input-group">
                        <input type="text" id="textSearch" class="form-control" placeholder="">
                        <div class="input-group-append">
                            <button class="btn btn-secondary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-12 col-md-6 d-flex align-items-end justify-content-end">
                <a class="btn btn-primary py-1" href="/question/add">Add new question</a>
            </div>
        </div>

        <!--Quiz listing table-->
        <div class="table-responsive my-4">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <!--Sorting arrow are displayed using the 'asc','dsc' classes-->
                    <th scope="col" class="sorting-header asc dsc">ID</th>
                    <th scope="col">Text</th>
                    <th scope="col">Type</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php
                if (isset($entities)):
                    foreach ($entities as $key => $values): ?>
                        <tr>
                            <th scope="row"><?php echo $values->getId();?></th>
                            <td><?php echo $values->getText();?></td>
                            <td><?php echo $values->getType();?></td>
                            <td class="text-center">
                                <a class="btn btn-primary py-1" href="/question/add/<?php echo $values->getId();?>">Edit</a>
                                <a class="btn btn-danger py-1" href="/question/delete/<?php echo $values->getId();?>">Delete</a>
                            </td>
                        </tr>
                <?php endforeach; endif;?>
                </tbody>
            </table>
        </div>

        <!--Pagination block-->
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item <?php if ($paginator->getCurrentPage() === 1): echo "disabled"; endif;?>">
                    <a class="page-link" href="<?php if ($paginator->getPreviousPage()): echo "/question?page=".$paginator->getPreviousPage(); endif;?>" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                <?php
                $page = 1;
                while ($page <= $paginator->getTotalpages()):
                    ?>
                    <li class="page-item <?php if($page === $paginator->getCurrentPage()): echo "active"; endif;?>"><a class="page-link" href="/question?page=<?php echo $page;?>"><?php echo $page;?></a></li>
                    <?php
                    $page++;
                endwhile;?>
                <li class="page-item <?php if ($paginator->getCurrentPage() === $paginator->getTotalpages()): echo "disabled"; endif;?>">
                    <a class="page-link" href="<?php if ($paginator->getNextPage()): echo "/question?page=".$paginator->getNextPage();; endif;?>">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>