<?php include "header.phtml" ?>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Quizzes</h1>
        </div>

        <!--Quizzes listing-->
        <table class="table table-hover my-4">
            <thead>
            <tr>
                <th scope="col">Quiz name</th>
                <th scope="col" class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php
            if (isset($entities)):
                foreach ($entities as $key => $values): ?>
                <tr>
                    <td><?php echo $values->getName();?></td>
                    <td class="text-center">
                        <a class="btn btn-primary py-1" href="/quizInstance/add/<?php echo $values->getId();?>">Start Quiz</a>
                    </td>
                </tr>
            <?php endforeach; endif;?>
            </tbody>
        </table>

    <!--Pagination block-->
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item <?php if ($paginator->getCurrentPage() === 1): echo "disabled"; endif;?>">
                    <a class="page-link" href="<?php if ($paginator->getPreviousPage()): echo "http://local.quiz.com/result?quiz=".$paginator->getPreviousPage(); endif;?>" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                <?php
                $page = 1;
                while ($page <= $paginator->getTotalpages()):
                    ?>
                    <li class="page-item <?php if($page === $paginator->getCurrentPage()): echo "active"; endif;?>"><a class="page-link" href="http://local.quiz.com/quiz?page=<?php echo $page;?>"><?php echo $page;?></a></li>
                    <?php
                    $page++;
                endwhile;?>
                <li class="page-item <?php if ($paginator->getCurrentPage() === $paginator->getTotalpages()): echo "disabled"; endif;?>">
                    <a class="page-link" href="<?php if ($paginator->getNextPage()): echo "http://local.quiz.com/result?quiz=".$paginator->getNextPage(); endif;?>">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>